In [17]:
#1. Create a 2D array of shape (4, 4) with numbers from 1 to 16 and display the first two rows.
import numpy as np
arr = np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [21]:
#2. Create a NumPy array of integers from 1 to 10, and find the sum of all elements.
arr1 = np.arange(1,10)
arr1
np.sum(arr1)

45

In [27]:
#3. Create an array of 20 random integers ranging from 0 to 100.
arr2 = np.random.randint(1,100,20)
arr2                

array([42, 95, 78,  6, 86, 91, 85, 97, 44, 96, 51, 71, 12, 85, 68, 54, 51,
       41, 31, 40])

In [39]:
#4. Create an array of 20 random integers ranging from 0 to 100 and find the minimum and maximum value.
arr3 = np.random.randint(1,100,20)
print(arr3)
print(np.min(arr3))
print(np.max(arr3))

[67 30 68 90 35  3 91 33 87 36  6 15 94 91 24 56 80 86 85 44]
3
94


In [59]:
#5. Create two 3x3 matrices and perform matrix addition and subtraction.
arra = np.array([[1,2,3],[4,5,6],[7,8,9]])
arrb = np.array([[5,6,7],[9,0,3],[1,2,8]])
print('first array\n',arra)
print('second array\n',arrb)
print('addition\n',arra+arrb)
print('substraction\n',arra-arrb)

first array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
second array
 [[5 6 7]
 [9 0 3]
 [1 2 8]]
addition
 [[ 6  8 10]
 [13  5  9]
 [ 8 10 17]]
substraction
 [[-4 -4 -4]
 [-5  5  3]
 [ 6  6  1]]


In [61]:
#6. Create two 3x3 matrices and perform matrix multiplication (both element-wise and dot product).
arrc = np.array([[5,3,4],[1,9,0],[2,1,3]])
arrd = np.array([[6,6,6],[7,7,7],[8,8,8]])
print('first array\n',arrc)
print('second array\n',arrd)
print('Multilication\n',arrc*arrd)
print('Division\n',arrc%arrd)

first array
 [[5 3 4]
 [1 9 0]
 [2 1 3]]
second array
 [[6 6 6]
 [7 7 7]
 [8 8 8]]
Multilication
 [[30 18 24]
 [ 7 63  0]
 [16  8 24]]
Division
 [[5 3 4]
 [1 2 0]
 [2 1 3]]


In [67]:
#7. Create an array of 12 elements and reshape it into a 3x4 matrix.
arr7 = np.arange(1,13).reshape(3,4)
arr7

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
#8. Create an array of 12 elements and reshape it into a 4x3 matrix.
arr8 = np.arange(1,13).reshape(4,3)
arr8

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [75]:
#9. Given an array [12, 4, 5, 23, 7, 18] sort the array in ascending order.
arr9 = np.array( [12, 4, 5, 23, 7, 18] )
np.sort(arr9)

array([ 4,  5,  7, 12, 18, 23])

In [ ]:
#10. Create an array of numbers from 0 to 50 with a step size of 5.
arr0 = np.linspace(